openapi: 3.1.1
info:
  title: API de exemplo do Instagram
  description: Uma API de teste
  version: 0.0.1

tags:
  - Usuarios
  - Postagens
  - Comentarios
  - Curtidas

paths:
  /api/usuarios:
    $ref: './paths/Usuario/Collection.yaml'
  /api/usuarios/{id}:
    $ref: './paths/Usuario/Item.yaml'

  /api/postagens:
    $ref: '.paths/Postagem/Collection.yaml'
  /api/postagens/{id}:
    $ref: '.paths/Postagem/Collection.yaml'

components:
  schemas:
    Usuario: 
      $ref: './components/Usuario.yaml'
    Postagem: 
      $ref: './components/Postagem.yaml'
    Comentario: 
      $ref: './components/Comentario.yaml'
    Curtida: 
      $ref: './components/Curtida.yaml'